# Generated by Django 2.0.4 on 2018-12-14 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_delivery', models.DateField(default=datetime.date.today)),
                ('serial_number', models.CharField(max_length=20)),
                ('firmware_version', models.CharField(max_length=50)),
                ('hardware_version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModelDirexioGPSTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_window_duration', models.IntegerField()),
                ('activity_window_count', models.IntegerField()),
                ('GPS_fix_timeout', models.IntegerField()),
                ('GPS_fix_interval', models.IntegerField()),
                ('GPS_fix_samples', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direxio_gps_tracker', to='inventory.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModelTestTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_window_duration', models.IntegerField()),
                ('some_other_activity', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_test_tracker', to='inventory.Device')),
            ],
        ),
        migrations.CreateModel(
            name='LoRaWAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevEUI', models.CharField(max_length=20)),
                ('activation_type', models.CharField(choices=[('OTAA', 'OTAA'), ('ABP', 'ABP')], max_length=4)),
                ('app_eui', models.CharField(max_length=50)),
                ('app_key', models.CharField(max_length=50)),
                ('nwkskey', models.CharField(max_length=50)),
                ('appskey', models.CharField(max_length=50)),
                ('devaddr', models.CharField(max_length=50)),
                ('adr', models.BooleanField()),
                ('data_rate', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)])),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='lorawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='inventory.LoRaWAN'),
        ),
        migrations.AddField(
            model_name='customer',
            name='devices',
            field=models.ManyToManyField(to='inventory.Device'),
        ),
    ]
