# Generated by Django 2.0.4 on 2018-12-14 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='devices',
            field=models.ManyToManyField(blank=True, to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_of_delivery',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='hardware_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='lorawan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='inventory.LoRaWAN'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='GPS_fix_interval',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='GPS_fix_samples',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='GPS_fix_timeout',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='activity_window_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='activity_window_duration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='direxio_gps_tracker', to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='devicemodeltesttracker',
            name='activity_window_duration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='devicemodeltesttracker',
            name='device',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_test_tracker', to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='devicemodeltesttracker',
            name='some_other_activity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='DevEUI',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='activation_type',
            field=models.CharField(blank=True, choices=[('OTAA', 'OTAA'), ('ABP', 'ABP')], max_length=4),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='app_eui',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='app_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='appskey',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='data_rate',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15)]),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='devaddr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='nwkskey',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
