# Generated by Django 2.1.4 on 2018-12-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20181214_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawan',
            name='adr',
            field=models.BooleanField(blank=True),
        ),
    ]
