# Generated by Django 2.1.4 on 2018-12-14 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181214_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_of_delivery',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='hardware_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='lorawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='inventory.LoRaWAN'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='GPS_fix_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='GPS_fix_samples',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='GPS_fix_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='activity_window_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='activity_window_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeldirexiogpstracker',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direxio_gps_tracker', to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='devicemodeltesttracker',
            name='activity_window_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodeltesttracker',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_test_tracker', to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='devicemodeltesttracker',
            name='some_other_activity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='DevEUI',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='adr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='app_eui',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='app_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='appskey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='devaddr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lorawan',
            name='nwkskey',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
