# Generated by Django 2.1.4 on 2018-12-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181214_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lorawan',
            name='activation_type',
            field=models.CharField(blank=True, choices=[('OTAA', 'OTAA'), ('ABP', 'ABP')], max_length=4, null=True),
        ),
    ]
