# Generated by Django 2.1.4 on 2018-12-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20181214_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='lorawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.LoRaWAN'),
        ),
    ]
