# Generated by Django 2.1.4 on 2018-12-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20181214_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='inventory.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModelToConfigurationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.ConfigurationField')),
                ('device_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.DeviceModel')),
            ],
        ),
    ]
