# Generated by Django 2.1.4 on 2018-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_configurationfield_devicemodel_devicemodeltoconfigurationfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurationfield',
            name='type',
        ),
        migrations.AddField(
            model_name='configurationfield',
            name='device_model',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
