# Generated by Django 2.1.4 on 2018-12-19 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20181219_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodeldirexiogpstracker',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicemodeltesttracker',
            name='device',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='devices',
        ),
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Device'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeviceModelDirexioGPSTracker',
        ),
        migrations.DeleteModel(
            name='DeviceModelTestTracker',
        ),
    ]
