# Generated by Django 2.1.4 on 2018-12-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20181219_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigurationFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicemodeltoconfigurationfield',
            name='configuration_field',
        ),
        migrations.RemoveField(
            model_name='devicemodeltoconfigurationfield',
            name='device_model',
        ),
        migrations.RenameField(
            model_name='configurationfield',
            old_name='value',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='inventory.DeviceModel'),
        ),
        migrations.DeleteModel(
            name='DeviceModelToConfigurationField',
        ),
        migrations.AddField(
            model_name='deviceconfigurationfieldvalue',
            name='configuration_field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.ConfigurationField'),
        ),
        migrations.AddField(
            model_name='deviceconfigurationfieldvalue',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.Device'),
        ),
    ]
