# Generated by Django 2.1.4 on 2018-12-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20181219_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device',
        ),
        migrations.AddField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='inventory.Customer'),
        ),
    ]
