# Generated by Django 2.1.4 on 2018-12-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_device_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfield',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuration_fields', to='inventory.DeviceModel'),
        ),
    ]
