# Generated by Django 2.1.4 on 2018-12-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20181219_1621'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deviceconfigurationfieldvalue',
            unique_together={('device', 'configuration_field')},
        ),
    ]
