# Generated by Django 2.1.4 on 2018-12-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20181219_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfigurationfieldvalue',
            name='configuration_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ConfigurationField'),
        ),
        migrations.AlterField(
            model_name='deviceconfigurationfieldvalue',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Device'),
        ),
    ]
